//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public long Id { get; set; }
        public long ParentId { get; set; }
        public string AccountName { get; set; }
        public long AccountCode { get; set; }
        public long MasterCode { get; set; }
        public int AccountType { get; set; }
        public int AccountLevel { get; set; }
        public long AccountCurrency { get; set; }
        public int Mezania3momia { get; set; }
        public int Reb7and5sara { get; set; }
        public long SerialNo { get; set; }
        public int H7sabElMotagra { get; set; }
        public Nullable<long> MasterAccountId { get; set; }
    }
}
