//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyData
    {
        public long Id { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyStyle { get; set; }
        public int CurrencyType { get; set; }
        public decimal CurrencyPrice { get; set; }
    }
}
