//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryDataHeader
    {
        public DeliveryDataHeader()
        {
            this.DeliveryDataDetails = new HashSet<DeliveryDataDetail>();
        }
    
        public long Id { get; set; }
        public long DeliveryNo { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public long ItemTypeId { get; set; }
        public int ProductionLineId { get; set; }
        public System.DateTime RecoredDate { get; set; }
        public long EmpId { get; set; }
    
        public virtual ICollection<DeliveryDataDetail> DeliveryDataDetails { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual ProductionLine ProductionLine { get; set; }
    }
}
