//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class division
    {
        public division()
        {
            this.EmployeeDatas = new HashSet<EmployeeData>();
            this.PurchaseOrderHeaders = new HashSet<PurchaseOrderHeader>();
        }
    
        public long Id { get; set; }
        public long DepartmentId { get; set; }
        public long Code { get; set; }
        public string Name { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ICollection<EmployeeData> EmployeeDatas { get; set; }
        public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; }
    }
}
