//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentHeader
    {
        public DocumentHeader()
        {
            this.DocumentDetails = new HashSet<DocumentDetail>();
        }
    
        public long Id { get; set; }
        public long DocNo { get; set; }
        public System.DateTime DocDate { get; set; }
        public long AccountId { get; set; }
        public decimal MasterAccountQty { get; set; }
        public long CostCenterId { get; set; }
        public string Notes { get; set; }
        public int DocType { get; set; }
        public int DocPaymentType { get; set; }
        public string HPriceInArabic { get; set; }
    
        public virtual ICollection<DocumentDetail> DocumentDetails { get; set; }
    }
}
