//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeData
    {
        public EmployeeData()
        {
            this.ClientDatas = new HashSet<ClientData>();
            this.DirectSellDatas = new HashSet<DirectSellData>();
        }
    
        public long Id { get; set; }
        public long Code { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string IdNo { get; set; }
        public int Sex { get; set; }
        public string Address { get; set; }
        public string FirstPhone { get; set; }
        public string SecondPhone { get; set; }
        public string FirstMobileNo { get; set; }
        public string SecondMobileNo { get; set; }
        public string FaxNo { get; set; }
        public string Email { get; set; }
        public long DepartmentId { get; set; }
        public long DivisionId { get; set; }
        public long JobId { get; set; }
        public System.DateTime StartJobDate { get; set; }
        public int MilitaryStatus { get; set; }
        public int InsuranceStatus { get; set; }
        public int MaritalStatus { get; set; }
        public long QualificationId { get; set; }
        public int Religion { get; set; }
        public int ContractType { get; set; }
        public long CountryId { get; set; }
        public long CityId { get; set; }
        public long GovernorateId { get; set; }
        public long AreaId { get; set; }
        public bool ISSalesRepresentative { get; set; }
        public long AccountId { get; set; }
    
        public virtual AreaData AreaData { get; set; }
        public virtual CityData CityData { get; set; }
        public virtual ICollection<ClientData> ClientDatas { get; set; }
        public virtual CountryData CountryData { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<DirectSellData> DirectSellDatas { get; set; }
        public virtual division division { get; set; }
        public virtual GovernorateData GovernorateData { get; set; }
        public virtual Job Job { get; set; }
        public virtual QualificationsData QualificationsData { get; set; }
    }
}
