//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncommingOrderData
    {
        public long Id { get; set; }
        public long RecordReceiptDetailsId { get; set; }
        public long AuditDetailsId { get; set; }
        public long IncommingOrderNo { get; set; }
        public decimal ItemPrice { get; set; }
        public decimal FreeItemPrice { get; set; }
        public long ItemTypeId { get; set; }
        public long LocationId { get; set; }
    
        public virtual AuditDetail AuditDetail { get; set; }
        public virtual ItemLocation ItemLocation { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual RecordReceiptDetail RecordReceiptDetail { get; set; }
    }
}
