//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemType
    {
        public ItemType()
        {
            this.DeliveryDataHeaders = new HashSet<DeliveryDataHeader>();
            this.DirectSellDatas = new HashSet<DirectSellData>();
            this.IncommingOrderDatas = new HashSet<IncommingOrderData>();
            this.ItemContentDetails = new HashSet<ItemContentDetail>();
            this.ItemLocations = new HashSet<ItemLocation>();
            this.Items = new HashSet<Item>();
            this.ItemTypeProdcutionLines = new HashSet<ItemTypeProdcutionLine>();
            this.PurchaseOrderHeaders = new HashSet<PurchaseOrderHeader>();
            this.RefluxHeaderDatas = new HashSet<RefluxHeaderData>();
        }
    
        public long Id { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public long AccountId { get; set; }
    
        public virtual ICollection<DeliveryDataHeader> DeliveryDataHeaders { get; set; }
        public virtual ICollection<DirectSellData> DirectSellDatas { get; set; }
        public virtual ICollection<IncommingOrderData> IncommingOrderDatas { get; set; }
        public virtual ICollection<ItemContentDetail> ItemContentDetails { get; set; }
        public virtual ICollection<ItemLocation> ItemLocations { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<ItemTypeProdcutionLine> ItemTypeProdcutionLines { get; set; }
        public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; }
        public virtual ICollection<RefluxHeaderData> RefluxHeaderDatas { get; set; }
    }
}
