//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemUnit
    {
        public ItemUnit()
        {
            this.ItemMovements = new HashSet<ItemMovement>();
            this.Items = new HashSet<Item>();
        }
    
        public long Id { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ItemMovement> ItemMovements { get; set; }
        public virtual ICollection<Item> Items { get; set; }
    }
}
