//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemContentHeader
    {
        public ItemContentHeader()
        {
            this.ItemContentDetails = new HashSet<ItemContentDetail>();
        }
    
        public long Id { get; set; }
        public int ItemType { get; set; }
        public long ProductionLineId { get; set; }
        public long ProductItemId { get; set; }
        public int ProductItemColor { get; set; }
    
        public virtual ICollection<ItemContentDetail> ItemContentDetails { get; set; }
    }
}
