//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.DeliveryDataDetails = new HashSet<DeliveryDataDetail>();
            this.DierctSellDetails = new HashSet<DierctSellDetail>();
            this.ExchangeRequestDetailsDatas = new HashSet<ExchangeRequestDetailsData>();
            this.ItemColorSelecteds = new HashSet<ItemColorSelected>();
            this.ItemContentDetails = new HashSet<ItemContentDetail>();
            this.ItemMovements = new HashSet<ItemMovement>();
            this.PurchaseOredrDetails = new HashSet<PurchaseOredrDetail>();
            this.RecordReceiptDetails = new HashSet<RecordReceiptDetail>();
            this.RefluxDetailsDatas = new HashSet<RefluxDetailsData>();
        }
    
        public long Id { get; set; }
        public long Code { get; set; }
        public string Name { get; set; }
        public long ItemTypeId { get; set; }
        public long ItemunitId { get; set; }
        public decimal LimitQty { get; set; }
        public int Sex { get; set; }
        public int ItemStatus { get; set; }
        public byte[] Image { get; set; }
        public string Specification { get; set; }
        public string Note { get; set; }
        public int ProductionLineId { get; set; }
    
        public virtual ICollection<DeliveryDataDetail> DeliveryDataDetails { get; set; }
        public virtual ICollection<DierctSellDetail> DierctSellDetails { get; set; }
        public virtual ICollection<ExchangeRequestDetailsData> ExchangeRequestDetailsDatas { get; set; }
        public virtual ICollection<ItemColorSelected> ItemColorSelecteds { get; set; }
        public virtual ICollection<ItemContentDetail> ItemContentDetails { get; set; }
        public virtual ICollection<ItemMovement> ItemMovements { get; set; }
        public virtual ItemStatus ItemStatu { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual ItemUnit ItemUnit { get; set; }
        public virtual ProductionLine ProductionLine { get; set; }
        public virtual SexData SexData { get; set; }
        public virtual ICollection<PurchaseOredrDetail> PurchaseOredrDetails { get; set; }
        public virtual ICollection<RecordReceiptDetail> RecordReceiptDetails { get; set; }
        public virtual ICollection<RefluxDetailsData> RefluxDetailsDatas { get; set; }
    }
}
