//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemLocation
    {
        public ItemLocation()
        {
            this.IncommingOrderDatas = new HashSet<IncommingOrderData>();
            this.ItemMovements = new HashSet<ItemMovement>();
        }
    
        public long Id { get; set; }
        public long ItemTypeId { get; set; }
        public int LocationCode { get; set; }
        public string LocationName { get; set; }
    
        public virtual ICollection<IncommingOrderData> IncommingOrderDatas { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual ICollection<ItemMovement> ItemMovements { get; set; }
    }
}
