//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalDetail
    {
        public long Id { get; set; }
        public long JournalId { get; set; }
        public long AccountId { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public long CostCenterId { get; set; }
        public string Notes { get; set; }
    
        public virtual JournalHeader JournalHeader { get; set; }
    }
}
