//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalHeader
    {
        public JournalHeader()
        {
            this.JournalDetails = new HashSet<JournalDetail>();
        }
    
        public long Id { get; set; }
        public long JournalCode { get; set; }
        public System.DateTime JournalDate { get; set; }
        public int JournalType { get; set; }
        public string Note { get; set; }
        public int Posted { get; set; }
        public long DocId { get; set; }
    
        public virtual ICollection<JournalDetail> JournalDetails { get; set; }
        public virtual JournalType JournalType1 { get; set; }
    }
}
