//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalType
    {
        public JournalType()
        {
            this.JournalHeaders = new HashSet<JournalHeader>();
        }
    
        public int Id { get; set; }
        public string JournalTypeName { get; set; }
    
        public virtual ICollection<JournalHeader> JournalHeaders { get; set; }
    }
}
