//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public long PageId { get; set; }
        public int OperationId { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual PagesName PagesName { get; set; }
        public virtual UserData UserData { get; set; }
    }
}
