//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointOfSale
    {
        public long Id { get; set; }
        public long Code { get; set; }
        public string Name { get; set; }
        public long CountryId { get; set; }
        public long CityId { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Note { get; set; }
    
        public virtual CityData CityData { get; set; }
        public virtual CountryData CountryData { get; set; }
    }
}
