//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOredrDetail
    {
        public PurchaseOredrDetail()
        {
            this.SupplyOrderDetails = new HashSet<SupplyOrderDetail>();
        }
    
        public long Id { get; set; }
        public long PurchaseOredeHeaderId { get; set; }
        public long ItemId { get; set; }
        public int ItemColorId { get; set; }
        public decimal Qty { get; set; }
        public int Status { get; set; }
        public decimal ConformQty { get; set; }
        public int IsChecked { get; set; }
        public string Note { get; set; }
        public int IsClosed { get; set; }
    
        public virtual ItemColor ItemColor { get; set; }
        public virtual Item Item { get; set; }
        public virtual PurchaseItemStatu PurchaseItemStatu { get; set; }
        public virtual PurchaseOrderHeader PurchaseOrderHeader { get; set; }
        public virtual ICollection<SupplyOrderDetail> SupplyOrderDetails { get; set; }
    }
}
