//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderHeader
    {
        public PurchaseOrderHeader()
        {
            this.PurchaseOredrDetails = new HashSet<PurchaseOredrDetail>();
        }
    
        public long Id { get; set; }
        public long PurchaseOrderNo { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public long DepartmentId { get; set; }
        public long DivisionId { get; set; }
        public long EmployeeId { get; set; }
        public long ItemTypeId { get; set; }
        public string Note { get; set; }
        public System.DateTime RecoredDate { get; set; }
        public long SupplierId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual division division { get; set; }
        public virtual ItemType ItemType { get; set; }
        public virtual ICollection<PurchaseOredrDetail> PurchaseOredrDetails { get; set; }
    }
}
