//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordReceiptDetail
    {
        public RecordReceiptDetail()
        {
            this.AuditDetails = new HashSet<AuditDetail>();
            this.IncommingOrderDatas = new HashSet<IncommingOrderData>();
        }
    
        public long Id { get; set; }
        public long RecordReceiptHeaderId { get; set; }
        public long ItemId { get; set; }
        public decimal QtyReceived { get; set; }
        public decimal FreeQty { get; set; }
        public long SupplyOrderDetailsId { get; set; }
        public string Indoor { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<AuditDetail> AuditDetails { get; set; }
        public virtual ICollection<IncommingOrderData> IncommingOrderDatas { get; set; }
        public virtual Item Item { get; set; }
        public virtual RecordReceiptHeader RecordReceiptHeader { get; set; }
        public virtual SupplyOrderDetail SupplyOrderDetail { get; set; }
    }
}
