//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordReceiptHeader
    {
        public RecordReceiptHeader()
        {
            this.RecordReceiptDetails = new HashSet<RecordReceiptDetail>();
        }
    
        public long Id { get; set; }
        public long RecordReceiptNo { get; set; }
        public System.DateTime RecordReceiptDate { get; set; }
        public System.DateTime RecDate { get; set; }
    
        public virtual ICollection<RecordReceiptDetail> RecordReceiptDetails { get; set; }
    }
}
