//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefluxHeaderData
    {
        public RefluxHeaderData()
        {
            this.RefluxDetailsDatas = new HashSet<RefluxDetailsData>();
        }
    
        public long Id { get; set; }
        public long RefluxNo { get; set; }
        public System.DateTime RefluxDate { get; set; }
        public long ItemTypeId { get; set; }
        public string Reason { get; set; }
        public long SupplierOrDepartmentId { get; set; }
        public long ExchangeOrPurchaseHeaderId { get; set; }
        public int OrderType { get; set; }
        public System.DateTime RecoredDate { get; set; }
        public long EmployeeId { get; set; }
    
        public virtual ItemType ItemType { get; set; }
        public virtual ICollection<RefluxDetailsData> RefluxDetailsDatas { get; set; }
    }
}
