//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierData
    {
        public SupplierData()
        {
            this.SupplyOrderHeaders = new HashSet<SupplyOrderHeader>();
        }
    
        public long Id { get; set; }
        public long Code { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Sex { get; set; }
        public string FirstPhone { get; set; }
        public string SecondPhone { get; set; }
        public string FirstMobile { get; set; }
        public string SecondMobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public long JobId { get; set; }
        public string IdNo { get; set; }
        public long CountryId { get; set; }
        public long CityId { get; set; }
        public long GovernorateId { get; set; }
        public long AreaId { get; set; }
        public int Status { get; set; }
        public long SupplierTypeId { get; set; }
        public long AccountId { get; set; }
    
        public virtual AreaData AreaData { get; set; }
        public virtual CityData CityData { get; set; }
        public virtual CountryData CountryData { get; set; }
        public virtual GovernorateData GovernorateData { get; set; }
        public virtual Job Job { get; set; }
        public virtual SupplierType SupplierType { get; set; }
        public virtual ICollection<SupplyOrderHeader> SupplyOrderHeaders { get; set; }
    }
}
