//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyOrderDetail
    {
        public SupplyOrderDetail()
        {
            this.RecordReceiptDetails = new HashSet<RecordReceiptDetail>();
        }
    
        public long Id { get; set; }
        public long SupplyOrderHeaderId { get; set; }
        public long PurchaseOrderDetailsId { get; set; }
        public decimal ItemPrice { get; set; }
        public string Note { get; set; }
    
        public virtual PurchaseOredrDetail PurchaseOredrDetail { get; set; }
        public virtual ICollection<RecordReceiptDetail> RecordReceiptDetails { get; set; }
        public virtual SupplyOrderHeader SupplyOrderHeader { get; set; }
    }
}
