//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAM.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public UserData()
        {
            this.Permissions = new HashSet<Permission>();
        }
    
        public long Id { get; set; }
        public long UserID { get; set; }
        public string NickName { get; set; }
        public string Password { get; set; }
        public int IsLock { get; set; }
    
        public virtual ICollection<Permission> Permissions { get; set; }
    }
}
